// Generado por construir.py a partir de datos/implantes.csv
// No editar a mano: los cambios se pierden en la siguiente ejecución.
const IMPLANTES = [
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-001",
    "forma": "redonda",
    "superficie": "lisa",
    "perfilMarca": "Perfil Bajo",
    "volumenCc": 255.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 3.3,
    "arcoCm": 5.8,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-002",
    "forma": "redonda",
    "superficie": "lisa",
    "perfilMarca": "Perfil Medio",
    "volumenCc": 295.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 3.9,
    "arcoCm": 6.1,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-003",
    "forma": "redonda",
    "superficie": "texturizada",
    "perfilMarca": "Perfil Medio",
    "volumenCc": 330.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 4.1,
    "arcoCm": 6.4,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-004",
    "forma": "redonda",
    "superficie": "texturizada",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 375.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 4.7,
    "arcoCm": 6.7,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-005",
    "forma": "redonda",
    "superficie": "lisa",
    "perfilMarca": "Perfil Bajo",
    "volumenCc": 300.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 3.5,
    "arcoCm": 6.2,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-006",
    "forma": "redonda",
    "superficie": "lisa",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 420.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 4.9,
    "arcoCm": 7.0,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-007",
    "forma": "redonda",
    "superficie": "texturizada",
    "perfilMarca": "Perfil Medio",
    "volumenCc": 460.0,
    "baseCm": 12.0,
    "alturaCm": 12.0,
    "proyeccionCm": 4.3,
    "arcoCm": 6.9,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-008",
    "forma": "anatomica",
    "superficie": "texturizada",
    "perfilMarca": "Altura Media / Proy Media",
    "volumenCc": 295.0,
    "baseCm": 10.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.6,
    "arcoCm": 5.5,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-009",
    "forma": "anatomica",
    "superficie": "texturizada",
    "perfilMarca": "Altura Media / Proy Alta",
    "volumenCc": 335.0,
    "baseCm": 11.0,
    "alturaCm": 10.0,
    "proyeccionCm": 4.4,
    "arcoCm": 5.9,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-010",
    "forma": "anatomica",
    "superficie": "texturizada",
    "perfilMarca": "Altura Alta / Proy Media",
    "volumenCc": 350.0,
    "baseCm": 11.0,
    "alturaCm": 11.5,
    "proyeccionCm": 3.8,
    "arcoCm": 6.3,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-011",
    "forma": "anatomica",
    "superficie": "nanotexturizada",
    "perfilMarca": "Altura Media / Proy Alta",
    "volumenCc": 390.0,
    "baseCm": 11.5,
    "alturaCm": 10.5,
    "proyeccionCm": 4.6,
    "arcoCm": 6.1,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  },
  {
    "marca": "DEMO",
    "linea": "Linea Demo",
    "referencia": "DEMO-012",
    "forma": "anatomica",
    "superficie": "nanotexturizada",
    "perfilMarca": "Altura Baja / Proy Media",
    "volumenCc": 270.0,
    "baseCm": 11.5,
    "alturaCm": 9.0,
    "proyeccionCm": 3.4,
    "arcoCm": 5.2,
    "gel": "Demo",
    "catalogo": "Datos ficticios de prueba",
    "pagina": null,
    "notas": "FICTICIO - no usar"
  }
];
