// Generado por construir.py a partir de datos/implantes.csv
// No editar a mano: los cambios se pierden en la siguiente ejecución.
const IMPLANTES = [
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "255 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 255.0,
    "baseCm": 9.2,
    "alturaCm": 9.2,
    "proyeccionCm": 5.6,
    "arcoCm": 7.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "225 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 225.0,
    "baseCm": 9.2,
    "alturaCm": 9.2,
    "proyeccionCm": 4.8,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "190 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 190.0,
    "baseCm": 9.2,
    "alturaCm": 9.2,
    "proyeccionCm": 4.0,
    "arcoCm": 6.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "155 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 155.0,
    "baseCm": 9.2,
    "alturaCm": 9.2,
    "proyeccionCm": 3.2,
    "arcoCm": 6.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "280 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 280.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 5.7,
    "arcoCm": 8.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "245 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 245.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 4.9,
    "arcoCm": 7.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "205 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 205.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 4.1,
    "arcoCm": 6.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "170 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 170.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.3,
    "arcoCm": 6.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "305 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 305.0,
    "baseCm": 9.8,
    "alturaCm": 9.8,
    "proyeccionCm": 5.8,
    "arcoCm": 8.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "270 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 270.0,
    "baseCm": 9.8,
    "alturaCm": 9.8,
    "proyeccionCm": 5.0,
    "arcoCm": 7.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "225 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 225.0,
    "baseCm": 9.8,
    "alturaCm": 9.8,
    "proyeccionCm": 4.2,
    "arcoCm": 7.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "185 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 185.0,
    "baseCm": 9.8,
    "alturaCm": 9.8,
    "proyeccionCm": 3.4,
    "arcoCm": 6.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "325 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 325.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 5.9,
    "arcoCm": 8.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "285 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 285.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 5.1,
    "arcoCm": 7.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "240 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 240.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 4.3,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "200 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 200.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 3.5,
    "arcoCm": 6.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "360 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 360.0,
    "baseCm": 10.4,
    "alturaCm": 10.4,
    "proyeccionCm": 6.0,
    "arcoCm": 8.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "305 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 305.0,
    "baseCm": 10.4,
    "alturaCm": 10.4,
    "proyeccionCm": 5.2,
    "arcoCm": 8.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "255 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 255.0,
    "baseCm": 10.4,
    "alturaCm": 10.4,
    "proyeccionCm": 4.4,
    "arcoCm": 7.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "215 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 215.0,
    "baseCm": 10.4,
    "alturaCm": 10.4,
    "proyeccionCm": 3.6,
    "arcoCm": 7.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "380 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 380.0,
    "baseCm": 10.7,
    "alturaCm": 10.7,
    "proyeccionCm": 6.1,
    "arcoCm": 9.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "335 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 335.0,
    "baseCm": 10.7,
    "alturaCm": 10.7,
    "proyeccionCm": 5.3,
    "arcoCm": 8.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "280 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 280.0,
    "baseCm": 10.7,
    "alturaCm": 10.7,
    "proyeccionCm": 4.5,
    "arcoCm": 7.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "240 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 240.0,
    "baseCm": 10.7,
    "alturaCm": 10.7,
    "proyeccionCm": 3.7,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "410 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 410.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 6.2,
    "arcoCm": 9.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "365 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 365.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 5.4,
    "arcoCm": 8.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "305 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 305.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 4.6,
    "arcoCm": 7.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "260 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 260.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 3.8,
    "arcoCm": 7.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "430 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 430.0,
    "baseCm": 11.3,
    "alturaCm": 11.3,
    "proyeccionCm": 6.3,
    "arcoCm": 9.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "390 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 390.0,
    "baseCm": 11.3,
    "alturaCm": 11.3,
    "proyeccionCm": 5.5,
    "arcoCm": 8.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "330 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 330.0,
    "baseCm": 11.3,
    "alturaCm": 11.3,
    "proyeccionCm": 4.7,
    "arcoCm": 8.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "275 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 275.0,
    "baseCm": 11.3,
    "alturaCm": 11.3,
    "proyeccionCm": 3.9,
    "arcoCm": 7.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "470 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 470.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 6.4,
    "arcoCm": 9.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "420 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 420.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 5.6,
    "arcoCm": 8.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "350 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 350.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 4.8,
    "arcoCm": 8.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "305 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 305.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 4.0,
    "arcoCm": 7.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "500 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 500.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 6.5,
    "arcoCm": 9.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "445 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 445.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 5.7,
    "arcoCm": 9.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "385 MD",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "MD (Moderate)",
    "volumenCc": 385.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 4.9,
    "arcoCm": 8.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "335 LO",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "LO (Low)",
    "volumenCc": 335.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 4.1,
    "arcoCm": 8.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "570 XH",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "XH (Extra High)",
    "volumenCc": 570.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 6.7,
    "arcoCm": 10.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Silimed",
    "linea": "Redondos",
    "referencia": "505 HI",
    "forma": "redonda",
    "superficie": "sin especificar",
    "superficieMarca": null,
    "perfilMarca": "HI (High)",
    "volumenCc": 505.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 5.9,
    "arcoCm": 9.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Superficie y línea sin especificar en el origen"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-130",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 130.0,
    "baseCm": 9.1,
    "alturaCm": 9.1,
    "proyeccionCm": 3.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-160",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 160.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-190",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 190.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 3.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-215",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 215.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 3.6,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-240",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 240.0,
    "baseCm": 10.9,
    "alturaCm": 10.9,
    "proyeccionCm": 3.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-270",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 270.0,
    "baseCm": 11.4,
    "alturaCm": 11.4,
    "proyeccionCm": 3.9,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-295",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 295.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 4.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-325",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 325.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 4.2,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-350",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 350.0,
    "baseCm": 12.2,
    "alturaCm": 12.2,
    "proyeccionCm": 4.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-370",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 370.0,
    "baseCm": 12.7,
    "alturaCm": 12.7,
    "proyeccionCm": 4.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-405",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 405.0,
    "baseCm": 12.8,
    "alturaCm": 12.8,
    "proyeccionCm": 4.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-440",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 440.0,
    "baseCm": 13.1,
    "alturaCm": 13.1,
    "proyeccionCm": 4.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-490",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 490.0,
    "baseCm": 13.6,
    "alturaCm": 13.6,
    "proyeccionCm": 4.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-545",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 545.0,
    "baseCm": 14.1,
    "alturaCm": 14.1,
    "proyeccionCm": 5.0,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-605",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 605.0,
    "baseCm": 14.4,
    "alturaCm": 14.4,
    "proyeccionCm": 5.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-645",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 645.0,
    "baseCm": 15.0,
    "alturaCm": 15.0,
    "proyeccionCm": 5.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "TMPX-755",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 755.0,
    "baseCm": 15.7,
    "alturaCm": 15.7,
    "proyeccionCm": 5.6,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-150",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 150.0,
    "baseCm": 8.4,
    "alturaCm": 8.4,
    "proyeccionCm": 4.2,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-175",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 175.0,
    "baseCm": 9.0,
    "alturaCm": 9.0,
    "proyeccionCm": 4.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-200",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 200.0,
    "baseCm": 9.4,
    "alturaCm": 9.4,
    "proyeccionCm": 4.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-230",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 230.0,
    "baseCm": 9.8,
    "alturaCm": 9.8,
    "proyeccionCm": 4.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-255",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 255.0,
    "baseCm": 10.1,
    "alturaCm": 10.1,
    "proyeccionCm": 4.9,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-285",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 285.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 5.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-325",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 325.0,
    "baseCm": 10.8,
    "alturaCm": 10.8,
    "proyeccionCm": 5.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-340",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 340.0,
    "baseCm": 11.1,
    "alturaCm": 11.1,
    "proyeccionCm": 5.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-365",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 365.0,
    "baseCm": 11.4,
    "alturaCm": 11.4,
    "proyeccionCm": 5.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-405",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 405.0,
    "baseCm": 11.6,
    "alturaCm": 11.6,
    "proyeccionCm": 5.9,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-425",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 425.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 5.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-455",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 455.0,
    "baseCm": 12.1,
    "alturaCm": 12.1,
    "proyeccionCm": 6.0,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-470",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 470.0,
    "baseCm": 12.3,
    "alturaCm": 12.3,
    "proyeccionCm": 5.9,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-515",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 515.0,
    "baseCm": 12.6,
    "alturaCm": 12.6,
    "proyeccionCm": 6.2,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-570",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 570.0,
    "baseCm": 13.2,
    "alturaCm": 13.2,
    "proyeccionCm": 6.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-620",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 620.0,
    "baseCm": 13.4,
    "alturaCm": 13.4,
    "proyeccionCm": 6.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-680",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 680.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 6.6,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-725",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 725.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 6.7,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "THPX-765",
    "forma": "redonda",
    "superficie": "texturizada",
    "superficieMarca": "SILTEX",
    "perfilMarca": "Perfil Alto",
    "volumenCc": 765.0,
    "baseCm": 14.7,
    "alturaCm": 14.7,
    "proyeccionCm": 6.7,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-130",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 130.0,
    "baseCm": 8.9,
    "alturaCm": 8.9,
    "proyeccionCm": 3.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-160",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 160.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.3,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-190",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 190.0,
    "baseCm": 10.0,
    "alturaCm": 10.0,
    "proyeccionCm": 3.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-215",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 215.0,
    "baseCm": 10.4,
    "alturaCm": 10.4,
    "proyeccionCm": 3.6,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-240",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 240.0,
    "baseCm": 10.8,
    "alturaCm": 10.8,
    "proyeccionCm": 3.7,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-270",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 270.0,
    "baseCm": 11.4,
    "alturaCm": 11.4,
    "proyeccionCm": 3.8,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-295",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 295.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 4.0,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-325",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 325.0,
    "baseCm": 11.9,
    "alturaCm": 11.9,
    "proyeccionCm": 4.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-350",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 350.0,
    "baseCm": 12.3,
    "alturaCm": 12.3,
    "proyeccionCm": 4.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-370",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 370.0,
    "baseCm": 12.6,
    "alturaCm": 12.6,
    "proyeccionCm": 4.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-405",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 405.0,
    "baseCm": 12.7,
    "alturaCm": 12.7,
    "proyeccionCm": 4.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-440",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 440.0,
    "baseCm": 13.1,
    "alturaCm": 13.1,
    "proyeccionCm": 4.5,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-490",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 490.0,
    "baseCm": 13.6,
    "alturaCm": 13.6,
    "proyeccionCm": 4.7,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-545",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 545.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 4.9,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-605",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 605.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 5.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-645",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 645.0,
    "baseCm": 14.9,
    "alturaCm": 14.9,
    "proyeccionCm": 5.1,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Mentor",
    "linea": "MemoryGel Xtra",
    "referencia": "SMPX-755",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "Liso",
    "perfilMarca": "Perfil Moderado Plus",
    "volumenCc": 755.0,
    "baseCm": 15.7,
    "alturaCm": 15.7,
    "proyeccionCm": 5.4,
    "arcoCm": null,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "El catálogo de redondos no publica arco vertical"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-105",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 105.0,
    "baseCm": 8.5,
    "alturaCm": 8.5,
    "proyeccionCm": 2.2,
    "arcoCm": 5.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-135",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 135.0,
    "baseCm": 8.5,
    "alturaCm": 8.5,
    "proyeccionCm": 3.1,
    "arcoCm": 5.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-145",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 145.0,
    "baseCm": 8.5,
    "alturaCm": 8.5,
    "proyeccionCm": 3.5,
    "arcoCm": 6.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-180",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 180.0,
    "baseCm": 8.5,
    "alturaCm": 8.5,
    "proyeccionCm": 4.0,
    "arcoCm": 6.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-125",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 125.0,
    "baseCm": 9.0,
    "alturaCm": 9.0,
    "proyeccionCm": 2.3,
    "arcoCm": 5.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-155",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 155.0,
    "baseCm": 9.0,
    "alturaCm": 9.0,
    "proyeccionCm": 3.3,
    "arcoCm": 6.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-175",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 175.0,
    "baseCm": 9.0,
    "alturaCm": 9.0,
    "proyeccionCm": 3.7,
    "arcoCm": 6.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-210",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 210.0,
    "baseCm": 9.0,
    "alturaCm": 9.0,
    "proyeccionCm": 4.2,
    "arcoCm": 6.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-140",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 140.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 2.4,
    "arcoCm": 5.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-180",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 180.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.4,
    "arcoCm": 6.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-205",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 205.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 3.9,
    "arcoCm": 6.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-240",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 240.0,
    "baseCm": 9.5,
    "alturaCm": 9.5,
    "proyeccionCm": 4.5,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-150",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 150.0,
    "baseCm": 9.75,
    "alturaCm": 9.75,
    "proyeccionCm": 2.4,
    "arcoCm": 5.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-190",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 190.0,
    "baseCm": 9.75,
    "alturaCm": 9.75,
    "proyeccionCm": 3.4,
    "arcoCm": 6.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-220",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 220.0,
    "baseCm": 9.75,
    "alturaCm": 9.75,
    "proyeccionCm": 4.0,
    "arcoCm": 6.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-260",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 260.0,
    "baseCm": 9.75,
    "alturaCm": 9.75,
    "proyeccionCm": 4.6,
    "arcoCm": 7.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-160",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 160.0,
    "baseCm": 10.0,
    "alturaCm": 10.0,
    "proyeccionCm": 2.5,
    "arcoCm": 5.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-205",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 205.0,
    "baseCm": 10.0,
    "alturaCm": 10.0,
    "proyeccionCm": 3.5,
    "arcoCm": 6.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-235",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 235.0,
    "baseCm": 10.0,
    "alturaCm": 10.0,
    "proyeccionCm": 4.1,
    "arcoCm": 7.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-280",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 280.0,
    "baseCm": 10.0,
    "alturaCm": 10.0,
    "proyeccionCm": 4.8,
    "arcoCm": 7.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-170",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 170.0,
    "baseCm": 10.25,
    "alturaCm": 10.25,
    "proyeccionCm": 2.5,
    "arcoCm": 5.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-215",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 215.0,
    "baseCm": 10.25,
    "alturaCm": 10.25,
    "proyeccionCm": 3.5,
    "arcoCm": 6.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-255",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 255.0,
    "baseCm": 10.25,
    "alturaCm": 10.25,
    "proyeccionCm": 4.2,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-300",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 300.0,
    "baseCm": 10.25,
    "alturaCm": 10.25,
    "proyeccionCm": 4.9,
    "arcoCm": 7.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-185",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 185.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 2.6,
    "arcoCm": 6.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-230",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 230.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 3.6,
    "arcoCm": 6.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-275",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 275.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 4.3,
    "arcoCm": 7.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-325",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 325.0,
    "baseCm": 10.5,
    "alturaCm": 10.5,
    "proyeccionCm": 5.1,
    "arcoCm": 8.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-205",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 205.0,
    "baseCm": 10.75,
    "alturaCm": 10.75,
    "proyeccionCm": 2.6,
    "arcoCm": 6.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-245",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 245.0,
    "baseCm": 10.75,
    "alturaCm": 10.75,
    "proyeccionCm": 3.7,
    "arcoCm": 7.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-295",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 295.0,
    "baseCm": 10.75,
    "alturaCm": 10.75,
    "proyeccionCm": 4.4,
    "arcoCm": 7.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-350",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 350.0,
    "baseCm": 10.75,
    "alturaCm": 10.75,
    "proyeccionCm": 5.2,
    "arcoCm": 8.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-220",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 220.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 2.7,
    "arcoCm": 6.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-265",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 265.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 3.8,
    "arcoCm": 7.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-315",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 315.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 4.5,
    "arcoCm": 7.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-380",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 380.0,
    "baseCm": 11.0,
    "alturaCm": 11.0,
    "proyeccionCm": 5.4,
    "arcoCm": 8.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-230",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 230.0,
    "baseCm": 11.25,
    "alturaCm": 11.25,
    "proyeccionCm": 2.7,
    "arcoCm": 6.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-285",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 285.0,
    "baseCm": 11.25,
    "alturaCm": 11.25,
    "proyeccionCm": 3.8,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-335",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 335.0,
    "baseCm": 11.25,
    "alturaCm": 11.25,
    "proyeccionCm": 4.6,
    "arcoCm": 7.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-410",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 410.0,
    "baseCm": 11.25,
    "alturaCm": 11.25,
    "proyeccionCm": 5.5,
    "arcoCm": 8.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-245",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 245.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 2.8,
    "arcoCm": 6.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-300",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 300.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 3.9,
    "arcoCm": 7.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-355",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 355.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 4.7,
    "arcoCm": 8.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-440",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 440.0,
    "baseCm": 11.5,
    "alturaCm": 11.5,
    "proyeccionCm": 5.7,
    "arcoCm": 9.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-260",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 260.0,
    "baseCm": 11.75,
    "alturaCm": 11.75,
    "proyeccionCm": 2.8,
    "arcoCm": 6.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-320",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 320.0,
    "baseCm": 11.75,
    "alturaCm": 11.75,
    "proyeccionCm": 3.9,
    "arcoCm": 7.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-375",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 375.0,
    "baseCm": 11.75,
    "alturaCm": 11.75,
    "proyeccionCm": 4.8,
    "arcoCm": 8.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-475",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 475.0,
    "baseCm": 11.75,
    "alturaCm": 11.75,
    "proyeccionCm": 5.8,
    "arcoCm": 9.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-275",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 275.0,
    "baseCm": 12.0,
    "alturaCm": 12.0,
    "proyeccionCm": 2.9,
    "arcoCm": 6.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-340",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 340.0,
    "baseCm": 12.0,
    "alturaCm": 12.0,
    "proyeccionCm": 4.0,
    "arcoCm": 7.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-400",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 400.0,
    "baseCm": 12.0,
    "alturaCm": 12.0,
    "proyeccionCm": 4.9,
    "arcoCm": 8.4,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-510",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 510.0,
    "baseCm": 12.0,
    "alturaCm": 12.0,
    "proyeccionCm": 6.0,
    "arcoCm": 9.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-290",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 290.0,
    "baseCm": 12.25,
    "alturaCm": 12.25,
    "proyeccionCm": 2.9,
    "arcoCm": 7.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-360",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 360.0,
    "baseCm": 12.25,
    "alturaCm": 12.25,
    "proyeccionCm": 4.0,
    "arcoCm": 7.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-425",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 425.0,
    "baseCm": 12.25,
    "alturaCm": 12.25,
    "proyeccionCm": 5.0,
    "arcoCm": 8.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-550",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 550.0,
    "baseCm": 12.25,
    "alturaCm": 12.25,
    "proyeccionCm": 6.1,
    "arcoCm": 9.6,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-310",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 310.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 3.0,
    "arcoCm": 7.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-380",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 380.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 4.1,
    "arcoCm": 7.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-450",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 450.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 5.1,
    "arcoCm": 8.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-590",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 590.0,
    "baseCm": 12.5,
    "alturaCm": 12.5,
    "proyeccionCm": 6.3,
    "arcoCm": 9.9,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-360",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 360.0,
    "baseCm": 13.0,
    "alturaCm": 13.0,
    "proyeccionCm": 3.1,
    "arcoCm": 7.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-425",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 425.0,
    "baseCm": 13.0,
    "alturaCm": 13.0,
    "proyeccionCm": 4.3,
    "arcoCm": 8.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-500",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 500.0,
    "baseCm": 13.0,
    "alturaCm": 13.0,
    "proyeccionCm": 5.3,
    "arcoCm": 9.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-650",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 650.0,
    "baseCm": 13.0,
    "alturaCm": 13.0,
    "proyeccionCm": 6.6,
    "arcoCm": 10.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-400",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 400.0,
    "baseCm": 13.5,
    "alturaCm": 13.5,
    "proyeccionCm": 3.2,
    "arcoCm": 7.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-475",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 475.0,
    "baseCm": 13.5,
    "alturaCm": 13.5,
    "proyeccionCm": 4.4,
    "arcoCm": 8.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-550",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 550.0,
    "baseCm": 13.5,
    "alturaCm": 13.5,
    "proyeccionCm": 5.5,
    "arcoCm": 9.5,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-725",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 725.0,
    "baseCm": 13.5,
    "alturaCm": 13.5,
    "proyeccionCm": 6.9,
    "arcoCm": 10.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-430",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 430.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 3.3,
    "arcoCm": 8.0,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-525",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 525.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 4.5,
    "arcoCm": 8.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-625",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 625.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 5.7,
    "arcoCm": 9.8,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-825",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 825.0,
    "baseCm": 14.0,
    "alturaCm": 14.0,
    "proyeccionCm": 7.2,
    "arcoCm": 11.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSM-475",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Mini",
    "volumenCc": 475.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 3.4,
    "arcoCm": 8.3,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSD-575",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Demi",
    "volumenCc": 575.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 4.6,
    "arcoCm": 9.1,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSF-700",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Full",
    "volumenCc": 700.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 5.9,
    "arcoCm": 10.2,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  },
  {
    "marca": "Motiva",
    "linea": "Round SilkSurface",
    "referencia": "RSC-925",
    "forma": "redonda",
    "superficie": "lisa",
    "superficieMarca": "SilkSurface",
    "perfilMarca": "Corsé",
    "volumenCc": 925.0,
    "baseCm": 14.5,
    "alturaCm": 14.5,
    "proyeccionCm": 7.5,
    "arcoCm": 11.7,
    "gel": null,
    "catalogo": "Aportado sin referencia de catálogo",
    "pagina": null,
    "notas": "Clasificación de SilkSurface como lisa, pendiente de confirmar"
  }
];
